# argocd-appsets/all-envs.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all
  namespace: argocd
spec:
  generators:
    # ① 集群维度：读 Git 文件 → 产生集群变量
    - git:
        repoURL: https://github.com/richard0147/k8s-ops.git
        revision: HEAD
        files:
          - path: "clusters/*.yaml"
    # ② 命名空间维度：扫描集群下所有 NS
    - git:
        repoURL: https://github.com/richard0147/k8s-ops.git
        revision: HEAD
        directories:
          - path: "overlays/{{clusterName}}/*"        # name = 集群名
  template:
    metadata:
      name: '{{clusterName}}-{{path.basename}}'   # cn-prod-vke-checkout
      labels:
        region: '{{labels.region}}'                # 来自 yaml
        cluster: '{{clusterName}}'
        env: '{{labels.env}}'                      # 来自 yaml
        appGroup: '{{path.basename}}'
    spec:
      project: '{{path.basename}}'                 # 或绑定具体 Project
      source:
        repoURL: https://github.com/richard0147/k8s-ops.git
        targetRevision: HEAD
        path: 'overlays/{{clusterName}}/{{path.basename}}'
      destination:
        server: '{{server}}'                # 来自 json
        namespace: '{{path.basename}}'
#      syncPolicy:
#        automated:
#          prune: true
#          selfHeal: {{if eq labels.env "stage"}}true{{else}}false{{end}}
#        syncOptions:
#          - CreateNamespace=true
  templatePatch: |
    spec:
    {{- if autoSync }}
      syncPolicy:
        automated:
          selfHeal: {{ selfHeal }}
    {{- end }}