# argocd-appsets/all-envs.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
#          - list:
#              elements:
#                - name: cn-stage
#                  server: https://kubernetes.default.svc
#                  labels:
#                    region: shanghai
#                    env: stage
#         # ① 集群维度：读 Git 文件 → 产生集群变量
          - git:
              repoURL: https://github.com/richard0147/k8s-ops.git
              revision: HEAD
              files:
                - path: "clusters/*.yaml"
          # ② 命名空间维度：扫描集群下所有 NS
#          - git:
#              pathParamPrefix: "ns"
#              repoURL: https://github.com/richard0147/k8s-ops.git
#              revision: HEAD
#              directories:
#                - path: "overlays/{{.name}}/*"        # name = 集群名
          - list:
              elements:
                - ns:
                    path:
                      basename: haivivi-test

  template:
    metadata:
      name: '{{.name}}-{{.ns.path.basename}}'   # cn-prod-haivivi-test
      labels:
        region: '{{.labels.region}}'
        cluster: '{{.name}}'
        env: '{{.labels.env}}'
        appGroup: '{{.ns.path.basename}}'
    spec:
      project: "{{.ns.path.basename}}"
      source:
        repoURL: https://github.com/richard0147/k8s-ops.git
        targetRevision: HEAD
        path: 'overlays/{{.name}}/{{.ns.path.basename}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.ns.path.basename}}'
      revisionHistoryLimit: 3
      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          enabled: {{ .autoSync }}
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}