apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: checkout
  namespace: argocd
spec:
  description: checkout 业务线
  sourceRepos:
    - https://github.com/<org>/k8s-gitops.git
  destinations:
    - namespace: 'checkout'
      server: '*'
  clusterResourceWhitelist: []