apiVersion: apps/v1
kind: Deployment
metadata:
  name: syw-test
spec:
  template:
    spec:
      containers:
        - name: syw-test
          image: cn-haivivi-cn-shanghai.cr.volces.com/libiary/nginx:1.25.5
