apiVersion: apps/v1
kind: Deployment
metadata:
  name: syw-test
spec:
  template:
    spec:
      containers:
        - name: syw-test
          env:
            - name: ENV
              value: stage
            - name: TEST1
              value: TEST1
