apiVersion: apps/v1
kind: Deployment
metadata:
  name: syw-test
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: syw-test
          env:
            - name: ENV
              value: stage
          resources:
            requests:
              cpu: 120m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
