apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: aiot
          envFrom:
            - secretRef:
                name: aiot-env
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
