apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: auth
          envFrom:
            - secretRef:
                name: auth-env
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
