apiVersion: apps/v1
kind: Deployment
metadata:
  name: bull-board
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bull-board
          envFrom:
            - secretRef:
                name: bull-board-env
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: 400m
              memory: 4Gi

