apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: pal
          envFrom:
            - secretRef:
                name: pal-env
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
