apiVersion: apps/v1
kind: Deployment
metadata:
  name: palapp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: palapp
          envFrom:
            - secretRef:
                name: palapp-env
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
