apiVersion: apps/v1
kind: Deployment
metadata:
  name: palgear
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: palgear
          envFrom:
            - secretRef:
                name: palgear-env
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1Gi
