apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: portal-web
          envFrom:
            - secretRef:
                name: portal-web-env
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
