apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: portal
          envFrom:
            - secretRef:
                name: portal-env
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1Gi
