apiVersion: apps/v1
kind: Deployment
metadata:
  name: push
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: push
          envFrom:
            - secretRef:
                name: push-env
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1Gi
