apiVersion: apps/v1
kind: Deployment
metadata:
  name: palapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: palapp
          envFrom:
            - secretRef:
                name: stage-env
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
